# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish Jar

on:
  workflow_dispatch:
    inputs:
      publish_forge:
        description: 'Publish Forge'
        required: true
        type: 'boolean'
        default: true
      publish_fabric:
        description: 'Publish Fabric'
        required: true
        type: 'boolean'
        default: true
      publish_to_curseforge:
        description: 'Publish to CurseForge'
        required: true
        type: 'boolean'
        default: false
      publish_to_modrinth:
        description: 'Publish to Modrinth'
        required: true
        type: 'boolean'
        default: false
      publish_github_release:
        description: 'Publish GitHub Release'
        required: true
        type: 'boolean'
        default: true

env:
  JAVA_VERSION: 17
  FABRIC_NAME: "Fabric 1.19.2-1.0.0 for Iris 1.6.9+"
  FORGE_NAME: "Forge 1.19.2-1.0.0 for Iris 1.6.9+"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish Fabric Github Release
        if: ${{ inputs.publish_fabric == 'true' && inputs.publish_github_release == 'true' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{secrets.PUBLISH_TOKEN}}"

          name: "${{env.FABRIC_NAME}}"
          changelog-file: CHANGELOG.md
          files: fabric/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar

          fail-mode: warn

      - name: Publish Fabric CurseForge
        if: ${{ inputs.publish_fabric == 'true' && inputs.publish_to_curseforge == 'true' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 659897
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          name: "${{env.FABRIC_NAME}}"
          changelog-file: CHANGELOG.md
          files: fabric/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar

          dependencies: |
            IrisShader@1.6.9(required){modrinth:iris}{curseforge:455508}
            CreateFabric(optional){modrithn:create-fabric}{curseforge:624165}

          fail-mode: warn

      - name: Publish Fabric Modrinth
        if: ${{ inputs.publish_fabric == 'true' && inputs.publish_to_modrinth == 'true' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: iris-flw-compat
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          name: "${{env.FABRIC_NAME}}"
          changelog-file: CHANGELOG.md
          files: fabric/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar

          dependencies: |
            IrisShader@1.6.9(required){modrinth:iris}{curseforge:455508}
            CreateFabric(optional){modrithn:create-fabric}{curseforge:624165}

          fail-mode: warn

      - name: Publish Forge Github Release
        if: ${{ inputs.publish_forge == 'true' && inputs.publish_to_modrinth == 'true' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{secrets.PUBLISH_TOKEN}}"

          name: "${{env.FORGE_NAME}}"
          changelog-file: CHANGELOG.md
          files: forge/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar

          fail-mode: warn

      - name: Publish Forge CurseForge
        if: ${{ inputs.publish_forge == 'true' && inputs.publish_to_curseforge == 'true' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 659897
          curseforge-token: "${{secrets.CURSEFORGE_TOKEN}}"

          name: "${{env.FORGE_NAME}}"
          changelog-file: CHANGELOG.md
          files: forge/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar

          dependencies: |
            Oculus@1.6.9(required){modrinth:oculus}{curseforge:581495}
            Create(optional){modrithn:create}{curseforge:328085}

          fail-mode: warn


      - name: Publish Forge Modrinth
        if: ${{ inputs.publish_forge == 'true' && inputs.publish_to_modrinth == 'true' }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: iris-flw-compat
          modrinth-token: "${{secrets.MODRINTH_TOKEN}}"

          name: "${{env.FORGE_NAME}}"
          changelog-file: CHANGELOG.md
          files: forge/build/libs/!(*-dev|*-sources|*-javadoc|*-shadow).jar

          dependencies: |
            Oculus@1.6.9(required){modrinth:oculus}{curseforge:581495}
            Create(optional){modrithn:create}{curseforge:328085}

          fail-mode: warn